import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  devNotesSidebar: [{ type: "autogenerated", dirName: "dev-notes" }],
  articlesSidebar: [{ type: "autogenerated", dirName: "articles" }],
  projectsSidebar: [{ type: "autogenerated", dirName: "projects" }],
};

export default sidebars;
