name: Deploy to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm run build
      - name: Deploy to samuelmaddox.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: SamuelMaddox/samuelmaddox.github.io
          publish_branch: main
          publish_dir: ./build
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
